import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Provider from "../utils/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//👇 Configure our font object
const roboto = Roboto({
  display: "swap",
  weight: ["100", "300", "400", "500", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${roboto.className} h-full bg-neutral-50 text-slate-900 dark:bg-scooter-900 dark:text-scooter-50`}
      >
        <Provider>
          <Navbar />
          <main className=" max-w-5xl mx-auto px-6">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
