import "./globals.css";
import SanityNavbar from "../components/SanityNavbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SanityNavbar />
        {children}
      </body>
    </html>
  );
}
